source 'https://github.com/CocoaPods/Specs.git'

target 'FDWaveformView', :exclusive => true do
  pod "FDWaveformView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FDWaveformView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase', '1.5'
  pod 'Expecta+Snapshots'
end
