name: "FDWaveformView CI"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "Example/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "Example/**"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  spm:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_16.1"
            runsOn: macos-15
            name: "macOS 15, Swift 6.0, SPM"
          - xcode: "Xcode_15.4"
            runsOn: macos-14
            name: "macOS 14, Swift 5.10, SPM"
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Swift Package Manager
        run: |
          set -o pipefail
          swift --version
          swift build
          swift test

  example-ios:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=18.1,name=iPhone 15"
            name: "Example iOS 18.1"
            xcode: "Xcode_16.1"
            runsOn: macos-15
          - destination: "OS=17.5,name=iPhone 15"
            name: "Example iOS 17.5"
            xcode: "Xcode_15.4"
            runsOn: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Example iOS
        run: |
          set -o pipefail
          cd Example
          xcodebuild -version
          xcodebuild -project Example.xcodeproj -scheme Example -destination "${{ matrix.destination }}" clean build